// <auto-generated />
using System;
using HouseRhiant.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HouseRiant.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260605212416_DropWorldLocations")]
    partial class DropWorldLocations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HouseRhiant.Api.Models.Building", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CapacityPersons")
                        .HasColumnType("integer");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ImagePosition")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsLivable")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int?>("StorageCapacityLbs")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Buildings");
                });

            modelBuilder.Entity("HouseRhiant.Api.Models.BuildingAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AssignmentType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("BuildingId")
                        .HasColumnType("integer");

                    b.Property<int>("ResidentId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.HasIndex("ResidentId");

                    b.ToTable("BuildingAssignments");
                });

            modelBuilder.Entity("HouseRhiant.Api.Models.CalendarEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Day")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DisplayDate")
                        .HasColumnType("text");

                    b.Property<int?>("EndDay")
                        .HasColumnType("integer");

                    b.Property<string>("EndWeek")
                        .HasColumnType("text");

                    b.Property<int?>("LinkedTaskId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int?>("RecurrenceGroupId")
                        .HasColumnType("integer");

                    b.Property<string>("Season")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ShortLabel")
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Week")
                        .HasColumnType("text");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LinkedTaskId");

                    b.ToTable("CalendarEvents");
                });

            modelBuilder.Entity("HouseRhiant.Api.Models.ChronicleEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EntryDate")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.ToTable("ChronicleEntries");
                });

            modelBuilder.Entity("HouseRhiant.Api.Models.ChronicleEntryNotableFigure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChronicleEntryId")
                        .HasColumnType("integer");

                    b.Property<int>("NotableFigureId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ChronicleEntryId");

                    b.HasIndex("NotableFigureId");

                    b.ToTable("ChronicleEntryNotableFigures");
                });

            modelBuilder.Entity("HouseRhiant.Api.Models.ChronicleEntryResident", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChronicleEntryId")
                        .HasColumnType("integer");

                    b.Property<int>("ResidentId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ChronicleEntryId");

                    b.HasIndex("ResidentId");

                    b.ToTable("ChronicleEntryResidents");
                });

            modelBuilder.Entity("HouseRhiant.Api.Models.ChronicleEntryTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChronicleEntryId")
                        .HasColumnType("integer");

                    b.Property<int>("TagId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ChronicleEntryId");

                    b.HasIndex("TagId");

                    b.ToTable("ChronicleEntryTags");
                });

            modelBuilder.Entity("HouseRhiant.Api.Models.EstateFinances", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BankBalanceTin")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("DorrinFundsTin")
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("LoanAmountTin")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("MoneyOnHandTin")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("TaxNotes")
                        .HasColumnType("text");

                    b.Property<decimal>("TaxRateTin")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("EstateFinances");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BankBalanceTin = 61m,
                            DorrinFundsTin = 0m,
                            LastUpdated = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            LoanAmountTin = 57022m,
                            MoneyOnHandTin = 0m,
                            TaxRateTin = 0m
                        });
                });

            modelBuilder.Entity("HouseRhiant.Api.Models.EstateTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssignedFamilyId")
                        .HasColumnType("integer");

                    b.Property<int?>("AssignedResidentId")
                        .HasColumnType("integer");

                    b.Property<int?>("BuildingId")
                        .HasColumnType("integer");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CompletedDate")
                        .HasColumnType("text");

                    b.Property<decimal?>("CostTin")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Outcome")
                        .HasColumnType("text");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("text");

                    b.Property<string>("PaymentNotes")
                        .HasColumnType("text");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Requirements")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TargetDate")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AssignedFamilyId");

                    b.HasIndex("AssignedResidentId");

                    b.HasIndex("BuildingId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("HouseRhiant.Api.Models.Family", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Allegiance")
                        .HasColumnType("text");

                    b.Property<string>("Expertise")
                        .HasColumnType("text");

                    b.Property<string>("HeadOfFamily")
                        .HasColumnType("text");

                    b.Property<string>("Motto")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Origin")
                        .HasColumnType("text");

                    b.Property<string>("Relationship")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Families");
                });

            modelBuilder.Entity("HouseRhiant.Api.Models.GameState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CurrentDay")
                        .HasColumnType("integer");

                    b.Property<string>("CurrentSeason")
                        .HasColumnType("text");

                    b.Property<string>("CurrentWeek")
                        .HasColumnType("text");

                    b.Property<int>("CurrentYear")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("GameStates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CurrentDay = 3,
                            CurrentSeason = "Brón: Bás",
                            CurrentYear = 58
                        });
                });

            modelBuilder.Entity("HouseRhiant.Api.Models.IncomeSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DailyYieldTin")
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("IncomeSources");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DailyYieldTin = 216m,
                            IsActive = true,
                            Name = "Rhiant Mine",
                            Notes = "Silver mine, 200 acres"
                        });
                });

            modelBuilder.Entity("HouseRhiant.Api.Models.Inventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Condition")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<decimal?>("EstimatedValue")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("Unit")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Inventories");
                });

            modelBuilder.Entity("HouseRhiant.Api.Models.NotableFigure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("Appearance")
                        .HasColumnType("text");

                    b.Property<string>("Faction")
                        .HasColumnType("text");

                    b.Property<int?>("FamilyId")
                        .HasColumnType("integer");

                    b.Property<string>("FirstMet")
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsAlive")
                        .HasColumnType("boolean");

                    b.Property<string>("KrellTribe")
                        .HasColumnType("text");

                    b.Property<string>("LastSeen")
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Race")
                        .HasColumnType("text");

                    b.Property<string>("Relationship")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .HasColumnType("text");

                    b.Property<string>("Skills")
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FamilyId");

                    b.ToTable("NotableFigures");
                });

            modelBuilder.Entity("HouseRhiant.Api.Models.PersonGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("PersonGroups");
                });

            modelBuilder.Entity("HouseRhiant.Api.Models.PersonGroupMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GroupId")
                        .HasColumnType("integer");

                    b.Property<int?>("NotableFigureId")
                        .HasColumnType("integer");

                    b.Property<int?>("ResidentId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("NotableFigureId");

                    b.HasIndex("ResidentId");

                    b.ToTable("PersonGroupMembers");
                });

            modelBuilder.Entity("HouseRhiant.Api.Models.Resident", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("Appearance")
                        .HasColumnType("text");

                    b.Property<int?>("BuildingId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("DailyPayRate")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("FamilyId")
                        .HasColumnType("integer");

                    b.Property<string>("Gender")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("KrellTribe")
                        .HasColumnType("text");

                    b.Property<string>("LandOwned")
                        .HasColumnType("text");

                    b.Property<string>("LevelOfRole")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Race")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("ShowOnHomePage")
                        .HasColumnType("boolean");

                    b.Property<string>("Skills")
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StatusOther")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TroopType")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.HasIndex("FamilyId");

                    b.ToTable("Residents");
                });

            modelBuilder.Entity("HouseRhiant.Api.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("HouseRhiant.Api.Models.BuildingAssignment", b =>
                {
                    b.HasOne("HouseRhiant.Api.Models.Building", "Building")
                        .WithMany("Assignments")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HouseRhiant.Api.Models.Resident", "Resident")
                        .WithMany("BuildingAssignments")
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Building");

                    b.Navigation("Resident");
                });

            modelBuilder.Entity("HouseRhiant.Api.Models.CalendarEvent", b =>
                {
                    b.HasOne("HouseRhiant.Api.Models.EstateTask", "LinkedTask")
                        .WithMany("CalendarEvents")
                        .HasForeignKey("LinkedTaskId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("LinkedTask");
                });

            modelBuilder.Entity("HouseRhiant.Api.Models.ChronicleEntryNotableFigure", b =>
                {
                    b.HasOne("HouseRhiant.Api.Models.ChronicleEntry", "ChronicleEntry")
                        .WithMany("EntryNotableFigures")
                        .HasForeignKey("ChronicleEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HouseRhiant.Api.Models.NotableFigure", "NotableFigure")
                        .WithMany()
                        .HasForeignKey("NotableFigureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChronicleEntry");

                    b.Navigation("NotableFigure");
                });

            modelBuilder.Entity("HouseRhiant.Api.Models.ChronicleEntryResident", b =>
                {
                    b.HasOne("HouseRhiant.Api.Models.ChronicleEntry", "ChronicleEntry")
                        .WithMany("EntryResidents")
                        .HasForeignKey("ChronicleEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HouseRhiant.Api.Models.Resident", "Resident")
                        .WithMany()
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChronicleEntry");

                    b.Navigation("Resident");
                });

            modelBuilder.Entity("HouseRhiant.Api.Models.ChronicleEntryTag", b =>
                {
                    b.HasOne("HouseRhiant.Api.Models.ChronicleEntry", "ChronicleEntry")
                        .WithMany("EntryTags")
                        .HasForeignKey("ChronicleEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HouseRhiant.Api.Models.Tag", "Tag")
                        .WithMany("EntryTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChronicleEntry");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("HouseRhiant.Api.Models.EstateTask", b =>
                {
                    b.HasOne("HouseRhiant.Api.Models.Family", "AssignedFamily")
                        .WithMany("Tasks")
                        .HasForeignKey("AssignedFamilyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HouseRhiant.Api.Models.Resident", "AssignedResident")
                        .WithMany("Tasks")
                        .HasForeignKey("AssignedResidentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HouseRhiant.Api.Models.Building", "Building")
                        .WithMany("Tasks")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AssignedFamily");

                    b.Navigation("AssignedResident");

                    b.Navigation("Building");
                });

            modelBuilder.Entity("HouseRhiant.Api.Models.NotableFigure", b =>
                {
                    b.HasOne("HouseRhiant.Api.Models.Family", "Family")
                        .WithMany("NotableFigures")
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Family");
                });

            modelBuilder.Entity("HouseRhiant.Api.Models.PersonGroupMember", b =>
                {
                    b.HasOne("HouseRhiant.Api.Models.PersonGroup", "Group")
                        .WithMany("Members")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HouseRhiant.Api.Models.NotableFigure", "NotableFigure")
                        .WithMany("GroupMemberships")
                        .HasForeignKey("NotableFigureId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("HouseRhiant.Api.Models.Resident", "Resident")
                        .WithMany("GroupMemberships")
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Group");

                    b.Navigation("NotableFigure");

                    b.Navigation("Resident");
                });

            modelBuilder.Entity("HouseRhiant.Api.Models.Resident", b =>
                {
                    b.HasOne("HouseRhiant.Api.Models.Building", "Building")
                        .WithMany("Residents")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HouseRhiant.Api.Models.Family", "Family")
                        .WithMany("Residents")
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Building");

                    b.Navigation("Family");
                });

            modelBuilder.Entity("HouseRhiant.Api.Models.Building", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Residents");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("HouseRhiant.Api.Models.ChronicleEntry", b =>
                {
                    b.Navigation("EntryNotableFigures");

                    b.Navigation("EntryResidents");

                    b.Navigation("EntryTags");
                });

            modelBuilder.Entity("HouseRhiant.Api.Models.EstateTask", b =>
                {
                    b.Navigation("CalendarEvents");
                });

            modelBuilder.Entity("HouseRhiant.Api.Models.Family", b =>
                {
                    b.Navigation("NotableFigures");

                    b.Navigation("Residents");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("HouseRhiant.Api.Models.NotableFigure", b =>
                {
                    b.Navigation("GroupMemberships");
                });

            modelBuilder.Entity("HouseRhiant.Api.Models.PersonGroup", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("HouseRhiant.Api.Models.Resident", b =>
                {
                    b.Navigation("BuildingAssignments");

                    b.Navigation("GroupMemberships");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("HouseRhiant.Api.Models.Tag", b =>
                {
                    b.Navigation("EntryTags");
                });
#pragma warning restore 612, 618
        }
    }
}
